name: Python CI with Poetry
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Python ${{ matrix.python-version }} and Poetry
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Run tests
      run: |
        make tests
    - name: Check style
      run: |
        make flake8